docs/get-started.md
packages/vxrn/src/create.ts

fix: typos

---

scripts/setup.ts

type error and errored on init run

fix: remove stout

---

CONTRIBUTING.md
reset.d.ts
scripts/setup.ts

add https://github.com/total-typescript/ts-reset

add: ts reset

---

docs/get-started.md

docs: add correct repack URl

---

package.json
yarn.lock

Upgraded `turbo` package.
Run `yarn build` inside root directory.

chore: upgrade `turbo` package

---

docs/get-started.md
examples/expo-router/dev.ts
examples/tamagui/dev.ts
packages/react-native-prebuilt/prebuild-react-native.ts
packages/vite-native-client/src/client.ts
packages/vite-native-hmr/src/hmr-client.ts
packages/vxrn/src/create.ts
packages/vxrn/src/dev/createDevServer.ts
packages/vxrn/src/nativePlugin.ts
scripts/release.ts
scripts/setup.ts

kill logs, replace with error or info

remove all console.log issues

---

examples/bare/tsconfig.json
examples/expo-router/tsconfig.json
examples/tamagui/tsconfig.json
packages/vxrn/package.json
packages/vxrn/src/create.ts
packages/vxrn/src/nativePlugin.ts
scripts/release.ts

In this Pull Request I've removed leftovers after brining code from Tamagui repo.

chore: remove tamagui leftovers

---

examples/bare/android/app/build.gradle
examples/bare/android/app/src/main/java/com/bare/MainApplication.kt
examples/bare/ios/Podfile
examples/bare/ios/Podfile.lock

Flipper is already deprecated.

chore(example): remove Flipper integration

---

examples/bare/biome.json
examples/expo-router/biome.json
examples/tamagui/biome.json
packages/create-vxrn/src/helpers/cloneStarter.ts
packages/create-vxrn/src/index.ts
packages/create-vxrn/src/steps/bare.ts
packages/create-vxrn/src/steps/expo-router.ts
packages/create-vxrn/src/steps/tamagui.ts
packages/expo-router/src/index.ts

- Properly replace placeholders in `bare` example (implementation based on RNC CLI). 
- Add instructions for `bare`
- Fixes path to `bare` example
To test thess changes you need to use template from this branch, to do so change this line:
https://github.com/natew/vxrn/blob/388ea2bdca8b5a9e27891146cfd4e55bb0ed4765/packages/create-vxrn/src/templates.ts#L30 to current branch name.

fix: adjustments to `create-vxrn`

---

.vscode/settings.json

Not to be overwritten by user’s language-specific settings.

chore(vscode): ensure that biome will be used

---

packages/vxrn/src/exports/dev.ts

chore: update “server running on” message

---

examples/vxs-plain/app/[user].tsx
examples/vxs-plain/app/_layout.tsx
examples/vxs-plain/app/example-tabs/_layout.tsx
examples/vxs-plain/app/example-tabs/index/[page_id].tsx
examples/vxs-plain/app/example-tabs/index/_layout.tsx
examples/vxs-plain/app/example-tabs/index/index.tsx
examples/vxs-plain/app/example-tabs/settings/_layout.tsx
examples/vxs-plain/app/example-tabs/settings/index.tsx
examples/vxs-plain/app/index.tsx
examples/vxs/app/user/[user].tsx
packages/vxrn/react-native-template.js

While merging this, we may need to use "Rebase and merge" since commits in this PR are somehow irrelative and should actually be 3 PRs instead of one.

VXS: make tab navigation work

---

packages/vxrn/react-native-template.js

One might encounter this `Maximum call stack size exceeded` runtime error on their React Native application:
```
🪵 [error] Error running module: "react-native-screens/lib/module/index.js"
◆ ./components/SearchBar.js RangeMaximum call stack size exceeded
Error:
◆ ./components/SearchBar.js RangeMaximum call stack size exceeded
at require (http://127.0.0.1:8081/index.bundle?platform=ios&dev=true&hot=false&transform.engine=hermes&transform.bytecode=true&transform.routerRoot=app:175:22)
at moduleFn2247 (http://127.0.0.1:8081/index.bundle?platform=ios&dev=true&hot=false&transform.engine=hermes&transform.bytecode=true&transform.routerRoot=app:333603:28)
at __getRequire (http://127.0.0.1:8081/index.bundle?platform=ios&dev=true&hot=false&transform.engine=hermes&transform.bytecode=true&transform.rou …
```

fix(vxrn): RN circular dependencies causing runtime call stack size exceeded error

---

packages/vxrn/src/exports/dev.ts
packages/vxrn/src/utils/fork/vite/build.ts
packages/vxrn/src/utils/fork/vite/constants.ts
packages/vxrn/src/utils/fork/vite/plugins.ts
packages/vxrn/src/utils/fork/vite/typeUtils.ts
packages/vxrn/src/utils/fork/vite/utils.ts
packages/vxrn/src/utils/getReactNativeBundle.ts
packages/vxrn/src/utils/getReactNativeConfig.ts
packages/vxrn/types/utils/fork/vite/build.d.ts
packages/vxrn/types/utils/fork/vite/constants.d.ts
packages/vxrn/types/utils/fork/vite/plugins.d.ts
packages/vxrn/types/utils/fork/vite/typeUtils.d.ts
packages/vxrn/types/utils/fork/vite/utils.d.ts
packages/vxrn/types/utils/getReactNativeConfig.d.ts

Performance improvements for serving the React Native bundle

---

examples/basic/db/connection.ts
examples/basic/db/drizzle.config.ts
examples/basic/db/migrations/0000_keen_mandarin.sql
examples/basic/db/migrations/meta/0000_snapshot.json
examples/basic/db/migrations/meta/_journal.json
examples/basic/db/run-migrations.ts
examples/basic/db/schema.ts
examples/basic/package.json
yarn.lock

- drizzle setup for basic example

feature(examples/basic): Drizzle + Schema

---

examples/basic/app/(feed)/_layout.tsx

[examples/basic] avoid title flashing when the data is loading

---

examples/one-recommended/code/db/drizzle.config.ts
examples/one-recommended/code/db/init.sh
examples/one-recommended/package.json
packages/one/src/getURL.ts

Recommended to "Rebase and merge" instead of squash in case we need to revert things.

Several fixes

---

examples/one-basic/package.json
packages/vxrn/src/exports/prebuild.ts

Recommended to "Rebase and merge" instead of squash in case we need to revert things.

prebuild: automatically remove ios/.xcode.env.local

---

examples/one-fullstack/components/HeadInfo.tsx

small thing leftover from what I assume is using the Tamagui site as a base

Replace Tamagui → One in Title tag

---

examples/one-recommended/.env.default
examples/one-tamagui/.env.default

Went through the cli, tried running: `yarn db:init`, updated the URL in the .env based off the docker-compose file, init command doesn't error.

add correct postgres url to env file

---

packages/one/src/cli/label-process.ts
packages/one/src/cli/run.ts
packages/one/src/serve.ts
packages/one/src/vite/build.ts
packages/one/src/vite/one.ts
packages/one/types/cli/label-process.d.ts

Label the One CLI processes for process monitoring tools:
`Onejs:[cli|serve|dev|build] > [process working directory]`

label one cli processes

---

examples/one-recommended/vite.config.ts
examples/one-tamagui/vite.config.ts
examples/one-zero/vite.config.ts
examples/test/vite.config.ts

vite config key needs to match `app.json` name to register the application.
steps:
- grepped project, found all `app.json` files using `one-example` name. Updated `vite.config.ts`
- successfully built the fullstack template after updating the vite config.
Note: I needed to clean and exit the app to make sure vite cache was cleaned.

update vite config for native build

---

examples/one-recommended/app/(feed)/_layout.tsx
examples/one-recommended/code/feed/FeedCard.tsx
packages/one/src/cleanUrl.ts

Recommend to rebase and merge since this contains another fix.
https://github.com/user-attachments/assets/370d6bd4-945d-429d-ab68-efe43cd9e9fe
https://github.com/user-attachments/assets/7b85f540-0cd3-4440-bcbb-edd2b3444de6

Fix example title flicker

---

packages/one/package.json
packages/one/src/cli.ts
yarn.lock

warn about Windows being unsupported

---

packages/vxrn/src/plugins/reactNativeHMRPlugin.ts
packages/vxrn/src/utils/getReactNativeBundle.ts

Recommend to rebase and merge since these fixes covers separated areas.

HMR Improvements 

---

packages/one/src/serve.ts
packages/one/src/vite/createFileSystemRouter.tsx
packages/vxrn/src/exports/dev.ts

Fixes #156.
Still need to add some regression tests I think.

fix: handle API redirects correctly

---

packages/one/src/cli.ts
packages/one/src/cli/patch.ts
packages/one/types/cli/patch.d.ts
packages/vxrn/expo-plugin.cjs
packages/vxrn/src/cli.ts
packages/vxrn/src/exports/patch.ts
packages/vxrn/src/index.ts
packages/vxrn/types/exports/patch.d.ts
packages/vxrn/types/index.d.ts

Related discussions: https://discord.com/channels/909986013848412191/1296623490182676564
Resolves / #192

Make EAS builds "just work"

---

packages/react-native-prebuilt/src/index.ts

fix(react-native-prebuilt): respect `.native.js` in @vxrn/vite-native-hmr

---

packages/resolve/src/index.tsx
packages/resolve/types/index.d.ts
packages/vxrn/src/exports/build.ts
packages/vxrn/src/utils/getBaseViteConfig.ts
packages/vxrn/src/utils/getViteServerConfig.ts
packages/vxrn/types/utils/getBaseViteConfig.d.ts

Fixes errors occurred in monorepo if react-native-web is not hoisted or the hoisted react-native-web is a different version.

fix(vxrn): resolve react-native-web from user’s app

---

examples/one-recommended/app/notifications+spa.tsx
packages/one/src/createHandleRequest.ts
packages/one/src/types.ts

Should fix https://github.com/onejs/one/issues/138
Needs testing

feat(one): add request to loader props

---

packages/create-vxrn/src/create.ts

feat(create): also set the app name in app.json

---

packages/vxrn/src/utils/depPatches.ts
packages/vxrn/src/utils/scanDepsToPreBundleForSsr.ts

make `react-native-vector-icons` work out of the box

---

packages/vxrn/src/utils/scanDepsToPreBundleForSsr.ts

scanDepsToPreBundleForSsr: try to also included entry points defined in package.json exports

---

packages/vxrn/src/utils/depPatches.ts

fix: don’t let `whatwg-url-without-unicode` break things

---

apps/onechat/config/tamagui/themes.ts
apps/onestack.dev/config/themes.ts
examples/one-tamagui/config/tamagui/themes.ts

Created a minimal PR to fix typos. I noticed typos in this repo so I'd be happy if this PR gets merged.

docs(theme): fix typos

---

apps/onestack.dev/data/docs/guides-eas.mdx
packages/vxrn/expo-plugin.cjs

Make Android builds on EAS

---

packages/vxrn/src/utils/swapPrebuiltReactModules.ts

fix: add more hard-coded react-native exports

---

packages/vxrn/react-native-template.js
packages/vxrn/src/utils/depPatches.ts
packages/vxrn/src/utils/getReactNativeConfig.ts

Fix other errors for `expo-image`

---

examples/one-tamagui/app/index.tsx

Also to avoid https://github.com/facebook/react-native/issues/48493.

Update Tamagui starter template

---

apps/onestack.dev/data/docs/components-Link.mdx

removed duplicate target prop definition

chore: update components-Link.mdx

---

packages/one/src/fork/_shared.ts
packages/one/src/fork/getPathFromState-mods.ts
packages/one/src/fork/getPathFromState.ts
packages/one/src/fork/getStateFromPath-mods.ts
packages/one/src/fork/getStateFromPath.ts
packages/one/types/fork/_shared.d.ts
packages/one/types/fork/getPathFromState-mods.d.ts
packages/one/types/fork/getStateFromPath-mods.d.ts
tests/test/app/routes/subpath/[...subpath].tsx
tests/test/routes.d.ts

fix(one): param in path not handled properly

---

examples/bare/package.json
examples/one-basic/package.json
examples/one-recommended/package.json
examples/one-tailwind/package.json
examples/one-tamagui/app.json
packages/vxrn/src/exports/prebuild.ts
yarn.lock

Context: https://discord.com/channels/1223009626400751671/1329197044702646342/1329687362904522804

feat(prebuild): warn about missing @react-native-community/cli dependency

---

packages/one/src/cli/build.ts
packages/one/src/vercel/build/buildVercelOutputDirectory.ts
tests/test/vercel.json

- adding check for middleware dist folder to make this optional when no middleware is available
- updating vercel.json for vercel template submission

fix(vercel): improve vercel deployments

---

packages/one/src/router/useScreens.tsx

feat: add error boundary for every route

---

packages/one/src/utils/redirect.ts
packages/one/types/utils/redirect.d.ts

Make redirect() type-safe

---

.github/actions/install/action.yml

Ci improvements

---

packages/one/src/Root.tsx
packages/one/src/createApp.native.tsx
packages/one/src/createApp.tsx
packages/one/src/router/FlagsContext.ts
packages/one/src/views/Navigator.tsx
packages/one/src/vite/one.ts
packages/one/src/vite/plugins/virtualEntryPlugin.ts
packages/one/src/vite/types.ts
packages/one/types/Root.d.ts
packages/one/types/createApp.d.ts
packages/one/types/createApp.native.d.ts
packages/one/types/router/FlagsContext.d.ts
packages/one/types/views/Navigator.d.ts
packages/one/types/vite/plugins/virtualEntryPlugin.d.ts
packages/one/types/vite/types.d.ts

```ts
// vite.config.ts
export default {
plugins: [
one({
router: {
experimental: {
preventLayoutRemounting: true, // ⬅️
},
},
```

feat(one): experimental prevent layout remounting

---

packages/one/src/router/sortRoutes.ts
packages/one/src/utils/globDir.ts
packages/one/src/vite/plugins/virtualEntryPlugin.ts

https://discord.com/channels/1223009626400751671/1357585331548983318/1357805963452879039

Various fixes

---

packages/one/src/utils/getPathnameFromFilePath.ts
packages/one/src/vercel/build/buildVercelOutputDirectory.ts
packages/one/src/vercel/build/generate/createApiServerlessFunction.ts
packages/one/src/vercel/build/generate/createSsrServerlessFunction.ts
packages/one/src/vercel/build/getPathFromRoute.ts

Vercel func's cannot be empty. If you're referencing all paths in the directory, you have to use index

Fix vercel deploy

---

apps/onestack.dev/data/docs/guides-tamagui.mdx

docs(guides-tamagui.mdx): grammar fix
