onejs/one

- docs/get-started.md
Fixed broken link to Repack docs
Before:
After:
> fix: fix broken link

- packages/react-native-prebuilt/prebuild-react-native.ts
In this PR I changed path to `vite-native-hmr` to one that is currently inside monorepo.
Run `yarn prebuild` inside `packages/react-native-prebuilt`, it should pass without any errors. 
```
❯ yarn prebuild
Prebuilding React Native (one time cost...)
```
> fix: use `vite-native-hmr` from `@vxrn` org

- packages/vxrn/src/vendor/repack/dev-server/src/createServer.ts
To properly support `@react-native-community/cli` a dev server needs to return a header called `X-React-Native-Project-Root` with path to the project root. 
```
❯ yarn ios
yarn run v1.22.19
$ react-native run-ios
info Another process is running on port 8081.
? Use port 8082 instead? › - Use arrow-keys. Return to submit.
❯   Yes
No
```
```
❯ yarn ios
yarn run v1.22.19
$ react-native run-ios
info A dev server is already running for this project on port 8081.
```
1. Bootstrap project with `npx react-native@latest init`
2. Do all necessary steps to setup `vxrn` inside project 
3. Start a dev server, and run `yarn ios` -> RN CLI should detect dev server on selected port.
> feat: add `X-React-Native-Project-Root` header to dev server

- examples/bare/tsconfig.json
- examples/expo-router/tsconfig.json
- examples/tamagui/tsconfig.json
- packages/vxrn/package.json
- packages/vxrn/src/create.ts
- packages/vxrn/src/dev/createDevServer.ts
- packages/vxrn/src/nativePlugin.ts
- packages/vxrn/src/vendor/repack/dev-server/src/createServer.ts
- scripts/release.ts
- yarn.lock
From React Native 0.73 there's a new Chrome Debugger - and the remote JS debugging is already deprecated.
> chore: remove debugger app

- packages/vxrn/src/dev/createDevServer.ts
Let's not mock `ios` as platform.
> fix: properly infer platform

- packages/vxrn/package.json
- packages/vxrn/src/dev/bindKeypressInput.ts
- packages/vxrn/src/dev/createDevServer.ts
- packages/vxrn/types/dev/bindKeypressInput.d.ts
- yarn.lock
added support for handling keypress inputs:
- `d` - to reload
- `r` - to refresh
- `c` - to clear terminal window 
- `ctrl + c` to quit the process 
https://github.com/natew/vxrn/assets/63900941/ebe5122f-3e08-460d-a2bd-2da97d406fc4
> feat: add handling keypress inputs

- examples/bare/index.js
- examples/bare/jest.config.js
When building app with React Native Community CLI, app is looking for `bare` module, in this PR I changed the module name to correctly match one included in `AppDelegate.mm`
https://github.com/natew/vxrn/blob/9b9bfff2780cdb583b1f314b30c54b3f15ae4ce7/examples/bare/ios/bare/AppDelegate.mm#L9
> fix(bare): main module name

- packages/vxrn/src/utils/getOptionsFilled.ts
fixes this:
```
🥺 couldn't patch [Error: ENOENT: no such file or directory, lstat '/home/aslemammad/oss/vxrn/packages/vxrn/dist/patches/react-native-screens+3.22.1.patch'] {
errno: -2,
code: 'ENOENT',
syscall: 'lstat',
path: '/home/aslemammad/oss/vxrn/packages/vxrn/dist/patches/react-native-screens+3.22.1.patch'
}
```
> fix: no such file patch

- examples/bare/android/app/build.gradle
- examples/bare/android/build.gradle
- examples/bare/android/gradle/wrapper/gradle-wrapper.properties
- examples/bare/ios/Podfile.lock
- examples/bare/ios/bare.xcodeproj/project.pbxproj
- examples/bare/ios/bare/AppDelegate.mm
- examples/bare/ios/bare/Info.plist
- examples/bare/ios/bare/PrivacyInfo.xcprivacy
When running native builds with `yarn android/ios` app on Android and iOS didn't build because of breaking changes that were introduced between 0.73 and 0.74 and not applied while upgrading React Native version recently:
> fix(bare): native builds

- packages/vxrn/package.json
- packages/vxrn/src/exports/clean.ts
- yarn.lock
It seems there isn’t a better way to do this for now since the [SystemError](https://nodejs.org/docs/latest-v22.x/api/errors.html#class-systemerror) class which defines `.code` property is not exported by Node.js.
> chore: refine TS types

- packages/vxrn/package.json
- packages/vxrn/run.mjs
Since the CommonJS files are not used anyway and might disturb JS debuggers from finding the correct built file to execute.
> chore: let vxrn build output only esm

- packages/react-native-prebuilt/src/index.ts
- packages/vite-flow/src/index.ts
- packages/vite-flow/types/index.d.ts
The JSX runtime between the pre-bundled `react-native` and the one being used during develop is inconsistent, causing annoying warnings to show.
The pre-bundled `react-native` is compiled to using production JSX, but while in development, development JSX is being used.
I’m seeing these `Each child in a list should have a unique "key" prop` warnings while running vxrn projects:
The warnings are coming from React Native’s internal components, such as `LogBoxLogNotification`
I checked the pre-built react native code (`node_modules/.vxrn/react-native.js`) and noticed that it’s using the production version of JSX runtime (`_jsxRuntime.jsx`) but not the development version (`_jsxRuntime.jsxDEV`):
```js
function LogBoxLogNotification(props) {
var totalLogCount = props.totalLogCount, level = …
```
> fix(react-native-prebuilt): inconsistent JSX runtime

- packages/vxrn/package.json
- packages/vxrn/src/plugins/expoManifestRequestHandlerPlugin.ts
- yarn.lock
* Adds a `picocolors` dependency to `vxrn.
* `picocolors` is also used by Vite but is bundled inside it. Seems that there's no way to access the bundled `picocolors` so we have to add that dependency.
* It seems that Babel is already using it as a dependency anyway.
* The `[vite]` prefix is not currently configurable unless we [create our own logger](https://github.com/vitejs/vite/blob/v6.0.0-alpha.18/packages/vite/src/node/logger.ts#L70-L79).
> chore(logger): use the vite way to log things

- packages/vxrn/src/utils/getReactNativeConfig.ts
* Only handle Expo packages with path matches, for now.
* Use [`order: 'pre’`](https://rollupjs.org/plugin-development/#build-hooks) to make sure JSX are handled before passing the code into SWC.
> fix: syntax errors with expo packages that uses JSX in .js files

- packages/vxrn/src/utils/getReactNativeBundle.ts
Fixes this kind of error on React Native with Supabase SDK:
```
🪵 [error] Error running module: "@supabase/node-fetch/lib/index.js"
Cannot read property 'prototype' of undefined
TypeError: Cannot read property 'prototype' of undefined
at anonymous (http://127.0.0.1:8081/index.bundle?platform=ios&dev=true&hot=false&transform.engine=hermes&transform.bytecode=true&transform.routerRoot=app:107110:64)
at module252 (http://127.0.0.1:8081/index.bundle?platform=ios&dev=true&hot=false&transform.engine=hermes&transform.bytecode=true&transform.routerRoot=app:107556:3)
at __getRequire (http://127.0.0.1:8081/index.bundle?platform=ios&dev=true&hot=false&transform.engine=hermes&transform.bytecode=true&transform.routerRoot=app:56:18)
at require (http://127.0.0.1:8081/index.bundle?platform=ios&dev=true&hot …
```
> fix: ignore `@supabase/node-fetch` from RN bundle

- packages/vxrn/src/utils/getReactNativeConfig.ts
Some packages such as `react-native-reanimated` will cause `getReactNativeBundle` to stuck with errors, this is an example:
```
transforming (1767) ../core/theme/dist/esm/_mutateTheme.native.js  ERROR  failed to read input source map: failed to parse inline source map url
index.js.map
Caused by:
relative URL without a base
at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.278.2/src/lib.rs:407
transforming (1959) ../core/web/dist/esm/_withStableStyle.native.js  ERROR  failed to read input source map: failed to parse inline source map url
index.js.map
Caused by:
relative URL without a base
at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.278.2/src/lib.rs:407
ERROR  failed to read input source map: failed to parse inline source map url …
```
> fix(rn): avoid "failed to read input source map: failed to parse inline source map url" errors on certain packages

- packages/vxrn/src/utils/swapPrebuiltReactModules.ts
Some packages, such as react-native-gesture-handler, are importing from react-native internals with named imports.
* [`PressabilityDebugView`](https://github.com/software-mansion/react-native-gesture-handler/blob/2.18.1/src/handlers/PressabilityDebugView.tsx#L2)
* [`customDirectEventTypes`](https://github.com/software-mansion/react-native-gesture-handler/blob/2.18.1/src/handlers/customDirectEventTypes.ts#L2), [usage](https://github.com/software-mansion/react-native-gesture-handler/blob/2.18.1/src/handlers/createHandler.tsx#L8).
This is a workaround to handle it case by case.
> fix(rn): export some name exports of RN internals

- packages/vite-native-swc/src/index.ts
- packages/vxrn/src/utils/getBaseViteConfig.ts
`examples/expo-reanimated`, run the app on native then edit `src/App.jsx`. After HMR a runtime error will occur:
```
🪵 [error] Module not found "/Users/z/Projects/vxrn/examples/expo-reanimated/node_modules/react-native-reanimated/lib/module/index.web.js" imported by "/src/App.jsx"
In importsMap:
{
"react/jsx-dev-runtime": "react/jsx-dev-runtime",
"react-native": "react-native",
"/Users/z/Projects/vxrn/examples/expo-reanimated/node_modules/react-native-reanimated/lib/module/index.web.js": "/Users/z/Projects/vxrn/examples/expo-reanimated/node_modules/react-native-reanimated/lib/module/index.web.js"
}
🪵 [error] TypeError: 0, _indexweb.useSharedValue is not a function (it is undefined)
This error is located at:
in App
in RCTView (created by View)
in View (created by AppContainer2)
in RCTView …
```
> Fix errors when RN HMR files that uses reanimated

- packages/react-native-prebuilt/src/index.ts
See explanation in code change.
Need to `rm -rf node_modules/.vxrn` in the project to rebuild the prebuilt React for this change to make effect.
> fix(react-native-prebuilt): prevent false warnings about `Each child in a list should have a unique "key" prop`

- packages/vxrn/src/exports/dev.ts
- packages/vxrn/src/utils/getReactNativeBundle.ts
Write/read Rollup cache on disk.
To enable `UNSTABLE_BUNDLE_CACHE`, `export UNSTABLE_BUNDLE_CACHE=true`. If enabled, we will also read the cached bundle from disk.
> Cache to disk

- packages/vite-native-swc/src/index.ts
Initially, I just wanted to suppress the error message printed to the terminal.
The error message is printed while SWC [calls its native bindings `bindings.transform()`](https://github.com/swc-project/swc/blob/v1.7.14/packages/core/src/index.ts#L231-L235), where the native bindings are imported from SWC binaries, on macOS it's `@swc/core-darwin-arm64/swc.darwin-arm64.node`.
Tried many tricky attempts like `process.stdout.write`, but those errors still print. I do not quite understand since wrapping the `bindings.transform()` in a try-catch won't work as expected too, it seems the cache cause will not be reached, but an error is still thrown.
Looked into the Rust code where the error might occur and finally discovered that we can just prevent that error from happening in the first place 😂 …
> fix(vxrn): swc panic with “called `Option::unwrap()` on a `None` value”

- packages/vxs/src/vite/resolveAPIRequest.ts
Fix for API routes hanging when an error is thrown from user-land +api.ts routes.
- Added rejection handler to the promise in resolveAPIRequest function
- Modified error handling to reject the promise on error
Implementation reason: Ensures that errors from userland API routes are properly handled and propagated, improving error management and debugging.
Files changed:
- packages/vxs/src/vite/resolveAPIRequest.ts
> fix(vite): Properly reject errors from userland API routes

- packages/vxrn/src/utils/getReactNativeConfig.ts
- packages/vxrn/src/utils/state.ts
- packages/vxrn/src/utils/swapPrebuiltReactModules.ts
I don't think the `if (isBuildingNativeBundle) {` logic in `swapPrebuiltReactModules.ts` is necessary now since we have Vite handling platform-specific extensions now I think. So I ended up removing it, tested it on a basic example, and it seems to be working well. If not, we should skip the last commit that removes it.
> fix: "EISDIR: illegal operation on a directory, read" when importing a file while there’s a dir with the same name

- examples/test/app/(blog)/blog/my-first-post.tsx
- examples/test/app/(marketing)/about.tsx
- examples/test/routes.d.ts
- packages/create-vxrn/src/create.ts
- packages/create-vxrn/src/index.ts
- packages/create-vxrn/src/steps/one.ts
- packages/one/src/cli.ts
- packages/one/test/routing.test.ts
- adds version output
- adds blank yarn.lock for yarn users on pre-install
- bonus: adds a test for (group) file-system routing, as I briefly saw an error there, but tests pass.
> Add version to cli tool

- examples/one-basic/package.json
- examples/one-tamagui/package.json
- yarn.lock
Since `one` is depending on `@react-navigation/native` and `@react-navigation/native` is depending on `react-native-screens` and `react-native-safe-area-context` which have native dependencies. See: https://reactnavigation.org/docs/7.x/getting-started#installing-dependencies-into-a-bare-react-native-project.
Can fix #133.
> [examples] dependencies with native code should be explicitly listed in package.json for native to work properly

- packages/one/src/createHandleRequest.ts
This pull request fixes a `import.meta.env` check on startup.
The bug was found and tested with `npx one` using Bun v1.1.30.
> Fix import.meta.env check

- packages/react-native-prebuilt/src/index.ts
For some reason it becomes `module.exports = require_react_development2();` instead of `module.exports = require_react_development();`. This update ensures both (and any other number) will be correctly patched.
> fix: prebuilt react not patched correctly

- packages/vxrn/package.json
- packages/vxrn/src/plugins/autoPreBundleDepsForSsrPlugin.ts
- packages/vxrn/src/utils/createDebugger.ts
- packages/vxrn/types/utils/createDebugger.d.ts
- yarn.lock
(Inspired by the Vite source code, powered by the [`debug`](https://www.npmjs.com/package/debug) package which is also used by Vite.)
```bash
DEBUG=vxrn:* yarn dev --clean
```
```bash
DEBUG=vxrn:auto-pre-bundle-deps-for-ssr yarn dev --clean
```
> [!NOTE]  
> Other debug logs are printed since old code are not migrated and they will print debug messages just if the keyword `"vxrn"` is included in `DEBUG`.
> basic debug log setup + debug logging for vxrn:auto-pre-bundle-deps-for-ssr

- packages/vite-native-swc/src/index.ts
- packages/vxrn/src/utils/getReactNativeConfig.ts
Context: https://discord.com/channels/1223009626400751671/1307758091533553676/1308884903362039880
Encountered error during dever server building an RN bundle, while using `@stytch/react-native` (`react-native-country-codes-picker` actually):
```
x Build failed in 3.67s
Error building React Native bundle: Error: [commonjs--resolver] Transform failed with 3 errors:
/Users/matthewwall/Downloads/pygmy/node_modules/react-native-country-codes-picker/index.tsx:21:4: ERROR: The symbol "RefreshRuntime" has already been declared
/Users/matthewwall/Downloads/pygmy/node_modules/react-native-country-codes-picker/index.tsx:22:4: ERROR: The symbol "prevRefreshReg" has already been declared
/Users/matthewwall/Downloads/pygmy/node_modules/react-native-country-codes-picker/index.tsx:23:4: ERROR: The symbol …
```
> fix: `the symbol "RefreshRuntime" has already been declared`

- apps/onestack.dev/data/docs/common-issues.mdx
Provide these common types of issues with an additional section for exposure and include common error messages to enhance searchability.
> docs: common RN package issues

- packages/vxrn/src/exports/dev.ts
- packages/vxrn/src/exports/patch.ts
Might be slower? But it can avoid Vite dep optimizing errors while Vite starts to pre-bundle things before all patches are applied. Such as:
> fix: wait until patches are applied before starting other stuff

- packages/vxrn/src/utils/getReactNativeConfig.ts
This is also part of the work for making a workaround for #252 possible.
Note: the final `define` will be like this, and I think there're no defines that aren't suitable to be defined on native:
```json
{
"process.env.NODE_ENV": "\"development\"",
"process.env.ONE_SERVER_URL": "\"http://0.0.0.0:8081\"",
"process.env.ONE_DEFAULT_RENDER_MODE": "\"ssg\"",
"import.meta.env.ONE_DEFAULT_RENDER_MODE": "\"ssg\"",
"import.meta.env.ONE_SERVER_URL": "\"http://0.0.0.0:8081\"",
"process.env.TAMAGUI_REACT_19": "\"1\"",
"process.env.ONE_CACHE_KEY": "\"52577802\"",
"import.meta.env.ONE_CACHE_KEY": "\"52577802\""
}
```
> feat: support user defined global constant replacements in RN

- packages/react-native-prebuilt/src/index.ts
- packages/vxrn/react-native-template.js
- packages/vxrn/src/utils/getReactNativeBundle.ts
React Native [lazy loads exports](https://github.com/facebook/react-native/blob/v0.76.0/packages/react-native/index.js#L102) like this:
```js
module.exports = {
get Button(): Button {
return require('./Libraries/Components/Button').default;
},
get FlatList(): FlatList {
return require('./Libraries/Lists/FlatList');
},
get Image(): Image {
return require('./Libraries/Image/Image');
},
get Modal(): Modal {
return require('./Libraries/Modal/Modal');
},
// ...
}
```
But we do [this](https://github.com/onejs/one/blob/v1.1.334/packages/react-native-prebuilt/src/index.ts#L233), which produces:
```js
var RN = run();
var Button = RN.Button;
var FlatList = RN.FlatList;
var Image = RN.Image;
var Modal = RN.Modal;
```
Which calls all the getter functions and forces the code to be loaded immediately - …
> fix(react-native-prebuilt): broken react native due to exports not being lazy loaded

- examples/one-basic/package.json
- yarn.lock
When I created a minimal example via a CLI locally, it didn't work because it was missing a dependency.  
`@react-navigation/drawer` relies on `reanimated`. it works on onejs locally because reanimated is already exists in its node_modules.
Run `npx expo install react-native-reanimated` and add `react-native-reanimated` dependency to `one-basic`.
> fix: error in minimal example

- apps/onestack.dev/app/docs/_layout.tsx
The `Edit this page on GitHub.` on `https://onestack.dev/docs/` points to the `one-js` github account, the branch `master` and the path `apps/site`
This PR corrects the account to `onejs`, branch to `main` and path to `apps/onestack.dev`
> docs: correct edit url

- apps/onestack.dev/features/search/DocSearch.tsx
When manually change theme, the input color will be invisible.
https://github.com/user-attachments/assets/b67bcf63-938b-4f11-be10-1bfe77b66b3f
seems it's due to `--colorHover` being missing on the docs website's css, not sure which color should be used exactly. I think we could just use `--color` instead. 
https://github.com/user-attachments/assets/76a1296c-c624-45e0-aaf3-4bcde80d37f5
>  fix: search input color

- next.md
- packages/react-native-prebuilt/src/index.ts
- packages/react-native-prebuilt/types/index.d.ts
- packages/vxrn/expo-js-native-debugging-plugin.cjs
- packages/vxrn/package.json
- packages/vxrn/react-native-template.js
- packages/vxrn/src/utils/getReactNativeBundle.ts
- packages/vxrn/src/utils/swapPrebuiltReactModules.ts
Based on #208.
The original implementation actually works, but by lazy loading, React `RefreshRuntime` won't get loaded in time, while in the RN bundle, it'll be used like this at the top level:
```js
var RefreshRuntime = __cachedModules["react-refresh/cjs/react-refresh-runtime.development"];
```
Which leads to errors:
```
Cannot read property 'createSignatureFunctionForTransform' of undefined
```
where that `undefined` is `RefreshRuntime`.
> React Native lazy imports

- packages/one/test/_setup.ts
- packages/resolve/src/index.tsx
The original implementaion of `@vxrn/resolve` will throw a `ERR_MODULE_NOT_FOUND` error in this case, for example:
```js
resolvePath('react-native-web', '/.../apps/my-app')
```
```
├── apps
│   └── my-app
│       └── node_modules
│           └── react-native-web
└── node_modules
└── @vxrn
└── resolve
└── index.mjs
```
It will only work if the path to resolve is also importable from the source location where `@vxrn/resolve` lives, for example:
```
└── apps
└── my-app
└── node_modules
├── @vxrn
│   └── resolve
│       └── index.mjs
└── react-native-web
```
> fix(resolve): resolve correctly if the path to resolve is not reachable from the source code file where the resolve package lives

- packages/vxrn/src/utils/swapPrebuiltReactModules.ts
Resolves https://discord.com/channels/1223009626400751671/1223009626400751676/1315991648404246528.
However, some issues still prevent `react-native-reanimated-carousel` from functioning properly.
> fix: returning `react-native/package.json` in `resolveId` stops subsequent plugins from resolving

- packages/react-native-prebuilt/src/index.ts
Resolves #195.
See https://github.com/onejs/one/issues/195#issuecomment-2531932837 for details.
> fix: fail to start if project path contains "js"

- packages/one/src/createApp.native.tsx
Since `polyfills-mobile` will access `setTimeout` that will be set by `react-native`.
> fix: react-native should be imported before polyfills-mobile

- .gitignore
- scripts/release.ts
Since yarn will handle workspace version cross-references (https://yarnpkg.com/features/workspaces#cross-references), and with npm we can have less trouble publishing.
> use yarn for packing and npm for publishing

- packages/vxrn/src/utils/getReactNativeConfig.ts
A workaround before we have #340.
> fix: tree-shake away the react-scan require manually if it’s not used

- packages/mdx/src/getMDX.ts
- packages/mdx/src/getMDXBySlug.tsx
- packages/mdx/src/index.ts
- packages/mdx/src/types.ts
- packages/mdx/types/getMDX.d.ts
- packages/mdx/types/getMDXBySlug.d.ts
- packages/mdx/types/index.d.ts
- packages/mdx/types/types.d.ts
I would like to use one to load mdx from a source other than the slug. This PR enables this by exporting `getMDX`.
Changes:
- Move `getMDX` to it's own file
- Move `getHeadings` and `readingTime` calls into `getMDX`
- Move UnifiedPlugin type to types file
- Export `getMDX` in index
> feat(mdx): export getmdx

- examples/one-zero/src/zero/zero.ts
Fix the type of useQuery hook.
This way is also supports `.one()` queries.
> fix type of useQuery

- packages/react-native-prebuilt/src/index.test.ts
- packages/react-native-prebuilt/src/index.ts
- yarn.lock
Simple test for a simple workaround.
> test(react-native-prebuilt): ensure we re-export all from react

- apps/onestack.dev/data/docs/components-LoadProgressBar.mdx
no code highlight since language is not mentioned in markdown
> chore: update components-LoadProgressBar.mdx

- packages/one/src/cli/build.ts
- packages/one/src/constants.ts
- packages/one/src/createHandleRequest.ts
- packages/one/src/useLoader.ts
- packages/one/src/utils/serverContext.tsx
- packages/one/src/vite/plugins/fileSystemRouterPlugin.tsx
- packages/one/types/constants.d.ts
- packages/one/types/utils/serverContext.d.ts
It seems that the global `__vxrnLoaderProps__` and `__vxrnLoaderData__` is now replaced with server context in #378.
The first commit made things work, while the second and third commit is a further proper fix.
> Fix `one-recommended` example broken on web due to `useLoader` behavior changes

- packages/compiler/src/index.ts
Fixes broken RN native builds.
Since when Xcode calls the bundle script, it won't be using `NODE_ENV`.
It would have been broken already, but luckily there's `forceJSX` which prevents this from happening, until [this change](https://github.com/onejs/one/pull/406/files#diff-99afc6baff732daa1f90f304742f5bddbd93b04441d389f4ec7b37e55914a79fL41).
> fix(compiler): should recognize production mode when used to build RN bundle

- apps/onestack.dev/components/TopNav.tsx
- apps/onestack.dev/features/theme/ThemeToggleButton.tsx
- Added `role="button"` to theme toggle buttons to make them keyboard accessible
- Ensures buttons can be reached via tab navigation
> Fix: Improve theme toggle button accessibility

- packages/one/src/fork/getStateFromPath.ts
We've already [modified `createNestedStateObject` to handle the hash](https://github.com/onejs/one/blob/v1.1.402/packages/one/src/fork/getStateFromPath.ts#L719-L730) but still need to pass that in. A better way may be to let `createNestedStateObject` get the hash from path data directly instead of the need to pass it every time.
> fix(router): link should correctly navigate with hash

- packages/one/src/vite/one.ts
Context: https://discord.com/channels/909986013848412191/1330712751739375708/1331662439581876306
> should always optimize `react/jsx-dev-runtime` if it’s there

- packages/vxrn/src/utils/scanDepsToOptimize.ts
Should fix the `Could not read from file: ReactNativeVersion` error on https://github.com/tamagui/tamagui/pull/3159.
> fix: `@tamagui/core/native-test` dep should not be optimized

- apps/onestack.dev/data/docs/exports-withLayoutContext.mdx
Hey!
Since a few releases, I've been keeping the React Navigation integration in a separate package. This PR reflects this change in the docs.
> docs: update react-native-bottom-tabs integration

- examples/one-tamagui/app/_layout.tsx
- examples/one-tamagui/app/index.tsx
- packages/compiler/package.json
- packages/compiler/src/index.ts
- packages/compiler/src/transformSWC.ts
- packages/one/src/router/useScreens.tsx
- packages/vite-native-client/src/client.ts
- packages/vite-native-hmr/src/hmr-client.ts
- packages/vite-native-hmr/types/hmr-client.d.ts
- packages/vxrn/src/plugins/reactNativeDevServer.ts
- packages/vxrn/src/plugins/reactNativeHMRPlugin.ts
- packages/vxrn/src/utils/connectedNativeClients.ts
- packages/vxrn/src/utils/getReactNativeBundle.ts
- packages/vxrn/types/plugins/reactNativeHMRPlugin.d.ts
- packages/vxrn/types/utils/connectedNativeClients.d.ts
- packages/vxrn/types/utils/getReactNativeBundle.d.ts
- yarn.lock
I was experimenting with fixing hot reload on root layout, that is tricky due to our wrapping and filtering of HTML. probably we need to fall back to a compiler method to inject the helper for the root layout.
This shows some other improvements for hmr @zetavg but problem is `modules` is empty for ios env, its only filled out for web. I think because we have two separate vite things going and only web is actually being used. We'd need a bigger refactor.
> showing new hotUpdate

- packages/one/src/fork/getStateFromPath.ts
- tests/test/app/layouts/index.tsx
- tests/test/app/layouts/nested-layout/with-slug-layout-folder/[layoutSlug]/_layout.tsx
- tests/test/app/layouts/nested-layout/with-slug-layout-folder/[layoutSlug]/index+ssr.tsx
- tests/test/routes.d.ts
- tests/test/tests/layouts.test.ts
I'm aware that in Chat app there's also the issue of not being able to navigate to such page via `Link`, but I haven't been able to repro that yet.
>  fix: useParams on page should also return dir slug params w/ layouts

- apps/onestack.dev/app/index.tsx
Closes [#501](https://github.com/onejs/one/issues/501)
Fixed the broken hyperlinks on the homepage that were leading to a white page when clicking "CLI" and "Middleware." The links now navigate to the correct sections of the page. Let me know if anything else needs adjustment!
> fix: redirect homepage hyperlinks correctly

- apps/devtools/biome.json
- apps/onestack.dev/biome.json
- biome.json
- examples/bare/biome.json
- examples/one-recommended/biome.json
- examples/one-recommended/package.json
- examples/one-tamagui/biome.json
- examples/one-tamagui/package.json
- examples/one-zero/biome.json
- examples/testflight/biome.json
- examples/testflight/package.json
- package.json
- packages/lllink/package.json
- packages/query-string/package.json
- packages/safe-area/package.json
- packages/vite-flow/package.json
- packages/vite-native-client/package.json
- packages/vxrn/package.json
- tests/sandbox/biome.json
- tests/test-cloudflare/biome.json
- tests/test-weird-deps/biome.json
- tests/test/biome.json
- yarn.lock
This pr updates biome v1.9.4. Since it seems that the format command is not used in the npm scripts, it has not been applied.
> chore: update biome to v1.9.4

- packages/one/src/vercel/build/buildVercelOutputDirectory.ts
- packages/one/src/vercel/build/generate/createApiServerlessFunction.ts
- packages/one/src/vercel/build/generate/createSsrServerlessFunction.ts
- tests/test/vercel.json
I met with Brandon at Vercel.
Vercel wants the .vercel/output and we have to point the vercel.json outputDir to the same location
This will build to the root directory and corrects the path for vercel.json outputDirectory.
Once this is merged, I need to run through our starters and make sure the SSR is deploying correctly.
> fix(build): modify build output directory for Vercel deployments

- apps/onestack.dev/data/docs/routing-modes.mdx
Fixed small details in the api route docs
- Removed `new` before `Response` – .json() static method is used to [create a json Response](https://developer.mozilla.org/en-US/docs/Web/API/Response/json_static#response_with_json_data), while .json() _instance_ method is used to read the json in the response. Confirmed this is working locally.
- Replaced `Handler` with `Endpoint`, because that seems to be the name of the type right now
> chore(docs): update api route docs

- packages/one/src/vercel/build/generate/createApiServerlessFunction.ts
> fix(vercel-deploy): fix API route build failure when react is used and project is not a monorepo

- packages/one/src/vite/plugins/generateFileSystemRouteTypesPlugin.tsx
- tests/test/app-cases/basic/app/page-in-basic-app-case.tsx
- tests/test/app-cases/basic/routes.d.ts
- tests/test/app-cases/basic/tsconfig.json
- tests/test/app-cases/not-found-at-root-with-assets/routes.d.ts
- tests/test/app-cases/not-found-at-root-with-assets/tsconfig.json
- tests/test/routes.d.ts
- tests/test/tsconfig.json
Getting rid of the annoying type changes after running tests.
> fix: generate `routes.d.ts` besides the app dir when it's customized

- packages/better-auth/src/index.ts
`loading` was getting set to `false` immediately by the `else { setState(empty); }` block. `useSession.subscribe` exposes `isPending`. Not sure if having a mutable `loading` variable is the right approach, but it seems to be working as expected now.
> Use isPending for better-auth loading state

- apps/onestack.dev/app/llms-full.txt+api.ts
This implementation isn't ideal, as it generates the document upon request every time, whereas it should be statically built.
But the problem with using an SSG route is that it cannot avoid the root `_layout` being applied.
> feat(site): llms-full.txt

- packages/one/src/router/getLinkingConfig.ts
Fixes an issue with `Tabs` layout trying to access the `config` on an `undefined` `this`. `getPathFromState` is being called such that it doesn't have access to `this`. Instead I extract the config to a variable which will be closed over and available to the function.
I also removed the `screens: []` since the config object already contains a screens field and would override it.
```
Error on route "(tabs)"
Cannot read properties of undefined (reading 'config')
TypeError: Cannot read properties of undefined (reading 'config')
at getPathFromState (http://localhost:8081/node_modules/.vite/deps/one.js?v=14332b62:7995:17)
at http://localhost:8081/node_modules/.vite/deps/one.js?v=14332b62:6485:18
at http://localhost:8081/node_modules/.vite/deps/one.js?v=14332b62:27955:21
at Array.map …
```
> Fix: getLinkingConfig undefined config
